version: '3.5'
services:     
  redis:
    image: redis:latest
    container_name: survey-cache
    restart: always
    command: redis-server --requirepass xxxxxxxxxxxxx --appendonly yes
    # command: redis-server --requirepass $PASSWORD --appendonly yes
    ports:
      - 6379:6379
    networks:
      - backend
  survey:
    image: go-jwt-access-refresh-token:latest
    container_name: survey
    depends_on:
      - redis
    ports:
      - 8881:8881
    networks:
      - backend
networks:
  backend:       

# parth /var/lib/docker/volumes
