survey: 
  port: ":8881"

db: 
  openDriver: "godror"
  connection: 
    "user=\"user\" 
     password=\"pass\" 
     connectString=\"db?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""

rdb:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

token: 
  issuer: ""
  secretKey: ""
